### ISSUE TITLE
OmnibotGamePadRC

### ISSUE THREAD

**Issue by mohammed666** [antonvh/Ev3Ps3GamePad#1]
How can i install the code and run ?

if you can 
write 
step by step

**Comment by antonvh** [comment]
Like it says in the readme?

The most recent ev3dev runs on python3 only. So might have to type
`python3  run_omnibot.py`

Don't forget to pair the ps3 controller to your ev3. It's pretty straightforward.

Als: if you work it out, maybe do a pull request with better installation instructions?

**Comment by dailydrifter** [comment]
I've been banging my head trying to run the code manually so I decided to run the .py program to verify if I'm the one typing in something wrong, and I received the same error:


robot@ev3dev:~/OmnibotGamePadRC$ python3 run_omnibot.py
  File "run_omnibot.py", line 10
    def clamp(n, (minn, maxn)):
                 ^
SyntaxError: invalid syntax

Which leads me to believe that the syntax is off and it should probably look like this:
   def clamp(n, minn, maxn):
But when I change the code to look like this I run into the missing MAXN attribute.

**Comment by antonvh** [comment]
There were some python 2.7 statements in de def. (Python 3 does not allow tuple unpacking in the declaration). I fixed those. Can you pull and test?

**Comment by dailydrifter** [comment]
awesome thanks! I'll try today!

**Comment by dailydrifter** [comment]
So I was able to get past the error, thanks for that update. I would have never figured that out.
Unfortunately, I couldn't get the controller to move the motors, but at least I wasn't receiving any errors. I figured I'd break down the code to work on one motor since I had your other code working.

I went line by line until I replaced:
self.front_motor.run_forever.......

With:
self.front_motor.run_direct.......

I'm going to guess run_forever is a 2.7 command? Either way I just got it to work with run_direct and I'm going remove the comment # on the other motors and see what happens.

Thanks for writing this code Anton and for supporting!

**Comment by antonvh** [comment]
Thanks for the heads-up. Will fix. It's legacy ev3dev.

FYI: run_direct is used in combination with duty_cycle_sp and run_forever with speed_sp. In the past you could mix them, but the library has become more strict.

Good luck!

**Comment by antonvh** [comment]
I changed everything to speed_sp. Can you pull and test?

**Comment by dailydrifter** [comment]
I was able to get my motors working like butter over the weekend. 

I'll pull your updated version this evening when I land. Might be later this evening.

Thanks for all the feedback. This is going to be the base of all our Jr FLL projects. I'll make sure I give you credit on our Facebook page!
